### ISSUE TITLE
Order of the metering column

### ISSUE THREAD

**Issue by waltercruz** [AlexNisnevich/synthi-js#3]
Hi! First of all, thank you for your amazing work!

Now, a simple request (maybe).

When reading the synthi manual, meter is the first column on the matrix row. In XILS4, it follow this pattern. In your synth, it's the 2nd column. Simple suggestion: bring the meter (scope) to the first column, and output 1 to the second column.

**Comment by AlexNisnevich** [comment]
Ah, I see. It looks like I ordered the meter/scope column based on its positioning in the SYNTHI AKS rather than the SYNTHI A.

No problem, I can fix that. The one tricky thing is I need to make sure that I don't break the patches while doing that, and that I modify all the help/readme text accordingly. I'll work on that this weekend.

**Comment by waltercruz** [comment]
aaah, ok, if it's in the same order like the aks, it's fine, I think :)

**Comment by AlexNisnevich** [comment]
Yeah, this is what the AKS patchboard looks like:
![image](https://cloud.githubusercontent.com/assets/415965/17007068/95ca560a-4e9a-11e6-854b-d72308ee1d20.png)

**Comment by waltercruz** [comment]
aaaah, ok. It's seems that the manual list them in the wrong order.

**Comment by AlexNisnevich** [comment]
No, I think this was actually something that got changed in the AKS. Note that the first few rows of the patchboard are also different in the AKS compared to the Synthi A.

Since I don't have `output ch1/2` columns like the Synthi AKS has, I guess I should move the meter/scope column for the sake of consistency. Otherwise I'm in a weird middle ground between the A and the AKS ...

**Comment by AlexNisnevich** [comment]
For comparison, here's the Synthi A patch matrix:
![image](https://cloud.githubusercontent.com/assets/415965/17007239/e09b7866-4e9b-11e6-8060-99e15c7777a7.png)

**Comment by waltercruz** [comment]
nice!
